/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsEntry {
  'clicks' : bigint,
  'views' : bigint,
  'projectId' : string,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'createdAt' : bigint,
  'productId' : string,
  'totalAmount' : bigint,
  'vendorId' : string,
  'buyerPrincipal' : Principal,
  'quantity' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'fulfilled' : null } |
  { 'declined' : null };
export interface Product {
  'id' : string,
  'imageBlob' : ExternalBlob,
  'inventory' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'vendorId' : string,
  'price' : bigint,
}
export interface ProjectEntry {
  'id' : string,
  'url' : string,
  'revenueShareConfigId' : [] | [string],
  'logo' : ExternalBlob,
  'name' : string,
  'description' : string,
  'category' : string,
}
export interface RevenueShareConfig {
  'id' : string,
  'participants' : Array<RevenueShareParticipant>,
}
export interface RevenueShareParticipant {
  'principal' : [] | [Principal],
  'stripeId' : [] | [string],
  'percentage' : bigint,
}
export interface RewardCampaign {
  'id' : string,
  'participants' : Array<Principal>,
  'rewardAmount' : bigint,
  'name' : string,
  'description' : string,
  'campaignType' : RewardCampaignType,
}
export type RewardCampaignType = { 'reward' : null } |
  { 'contest' : null } |
  { 'workshop' : null } |
  { 'referral' : null } |
  { 'earning' : null } |
  { 'education' : null } |
  { 'commission' : null } |
  { 'airdrop' : null } |
  { 'bonus' : null } |
  { 'special' : null } |
  { 'volunteer' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'preferences' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : string,
  'bio' : string,
  'displayName' : string,
  'ownerPrincipal' : Principal,
  'createdAt' : bigint,
}
export interface Wallet {
  'stripeBalance' : bigint,
  'icpBalance' : bigint,
  'transactionHistory' : Array<string>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProjectEntry' : ActorMethod<[ProjectEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeRewardCampaign' : ActorMethod<[string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[string, string, bigint], string>,
  'createProduct' : ActorMethod<
    [string, string, string, bigint, ExternalBlob, bigint],
    string
  >,
  'createRevenueShareConfig' : ActorMethod<[RevenueShareConfig], undefined>,
  'createRewardCampaign' : ActorMethod<[RewardCampaign], undefined>,
  'createVendor' : ActorMethod<[string, string], string>,
  'creditVendor' : ActorMethod<[string, bigint], undefined>,
  'depositToWallet' : ActorMethod<[bigint, bigint], undefined>,
  'getAllAnalytics' : ActorMethod<[], Array<AnalyticsEntry>>,
  'getAnalytics' : ActorMethod<[string], [] | [AnalyticsEntry]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyVendor' : ActorMethod<[], [] | [Vendor]>,
  'getMyVendorBalance' : ActorMethod<[], bigint>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getProjectEntries' : ActorMethod<[], Array<ProjectEntry>>,
  'getRevenueShareConfig' : ActorMethod<[string], [] | [RevenueShareConfig]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendorById' : ActorMethod<[string], [] | [Vendor]>,
  'getWallet' : ActorMethod<[], [] | [Wallet]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'joinRewardCampaign' : ActorMethod<[string], undefined>,
  'listMyOrders' : ActorMethod<[], Array<Order>>,
  'listOrdersByVendor' : ActorMethod<[string], Array<Order>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listProductsByVendor' : ActorMethod<[string], Array<Product>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'trackProjectClick' : ActorMethod<[string], undefined>,
  'trackProjectView' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [string, string, string, bigint, ExternalBlob, bigint],
    undefined
  >,
  'updateRevenueShareConfig' : ActorMethod<[RevenueShareConfig], undefined>,
  'withdrawFromWallet' : ActorMethod<[bigint, bigint], undefined>,
  'withdrawVendorBalance' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];