/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProjectEntry = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'revenueShareConfigId' : IDL.Opt(IDL.Text),
  'logo' : ExternalBlob,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const RevenueShareParticipant = IDL.Record({
  'principal' : IDL.Opt(IDL.Principal),
  'stripeId' : IDL.Opt(IDL.Text),
  'percentage' : IDL.Nat,
});
export const RevenueShareConfig = IDL.Record({
  'id' : IDL.Text,
  'participants' : IDL.Vec(RevenueShareParticipant),
});
export const RewardCampaignType = IDL.Variant({
  'reward' : IDL.Null,
  'contest' : IDL.Null,
  'workshop' : IDL.Null,
  'referral' : IDL.Null,
  'earning' : IDL.Null,
  'education' : IDL.Null,
  'commission' : IDL.Null,
  'airdrop' : IDL.Null,
  'bonus' : IDL.Null,
  'special' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const RewardCampaign = IDL.Record({
  'id' : IDL.Text,
  'participants' : IDL.Vec(IDL.Principal),
  'rewardAmount' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'campaignType' : RewardCampaignType,
});
export const AnalyticsEntry = IDL.Record({
  'clicks' : IDL.Nat,
  'views' : IDL.Nat,
  'projectId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'preferences' : IDL.Vec(IDL.Text),
});
export const Vendor = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'ownerPrincipal' : IDL.Principal,
  'createdAt' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'fulfilled' : IDL.Null,
  'declined' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : IDL.Nat,
  'productId' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'vendorId' : IDL.Text,
  'buyerPrincipal' : IDL.Principal,
  'quantity' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Wallet = IDL.Record({
  'stripeBalance' : IDL.Nat,
  'icpBalance' : IDL.Nat,
  'transactionHistory' : IDL.Vec(IDL.Text),
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'imageBlob' : ExternalBlob,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Nat,
  'description' : IDL.Text,
  'vendorId' : IDL.Text,
  'price' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProjectEntry' : IDL.Func([ProjectEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeRewardCampaign' : IDL.Func([IDL.Text], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'createRevenueShareConfig' : IDL.Func([RevenueShareConfig], [], []),
  'createRewardCampaign' : IDL.Func([RewardCampaign], [], []),
  'createVendor' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'creditVendor' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'depositToWallet' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getAllAnalytics' : IDL.Func([], [IDL.Vec(AnalyticsEntry)], ['query']),
  'getAnalytics' : IDL.Func([IDL.Text], [IDL.Opt(AnalyticsEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyVendor' : IDL.Func([], [IDL.Opt(Vendor)], ['query']),
  'getMyVendorBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getProjectEntries' : IDL.Func([], [IDL.Vec(ProjectEntry)], ['query']),
  'getRevenueShareConfig' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RevenueShareConfig)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendorById' : IDL.Func([IDL.Text], [IDL.Opt(Vendor)], ['query']),
  'getWallet' : IDL.Func([], [IDL.Opt(Wallet)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'joinRewardCampaign' : IDL.Func([IDL.Text], [], []),
  'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listOrdersByVendor' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProductsByVendor' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'trackProjectClick' : IDL.Func([IDL.Text], [], []),
  'trackProjectView' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob, IDL.Nat],
      [],
      [],
    ),
  'updateRevenueShareConfig' : IDL.Func([RevenueShareConfig], [], []),
  'withdrawFromWallet' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'withdrawVendorBalance' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProjectEntry = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'revenueShareConfigId' : IDL.Opt(IDL.Text),
    'logo' : ExternalBlob,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const RevenueShareParticipant = IDL.Record({
    'principal' : IDL.Opt(IDL.Principal),
    'stripeId' : IDL.Opt(IDL.Text),
    'percentage' : IDL.Nat,
  });
  const RevenueShareConfig = IDL.Record({
    'id' : IDL.Text,
    'participants' : IDL.Vec(RevenueShareParticipant),
  });
  const RewardCampaignType = IDL.Variant({
    'reward' : IDL.Null,
    'contest' : IDL.Null,
    'workshop' : IDL.Null,
    'referral' : IDL.Null,
    'earning' : IDL.Null,
    'education' : IDL.Null,
    'commission' : IDL.Null,
    'airdrop' : IDL.Null,
    'bonus' : IDL.Null,
    'special' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const RewardCampaign = IDL.Record({
    'id' : IDL.Text,
    'participants' : IDL.Vec(IDL.Principal),
    'rewardAmount' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'campaignType' : RewardCampaignType,
  });
  const AnalyticsEntry = IDL.Record({
    'clicks' : IDL.Nat,
    'views' : IDL.Nat,
    'projectId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'preferences' : IDL.Vec(IDL.Text),
  });
  const Vendor = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'ownerPrincipal' : IDL.Principal,
    'createdAt' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'fulfilled' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : IDL.Nat,
    'productId' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'vendorId' : IDL.Text,
    'buyerPrincipal' : IDL.Principal,
    'quantity' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Wallet = IDL.Record({
    'stripeBalance' : IDL.Nat,
    'icpBalance' : IDL.Nat,
    'transactionHistory' : IDL.Vec(IDL.Text),
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'imageBlob' : ExternalBlob,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Nat,
    'description' : IDL.Text,
    'vendorId' : IDL.Text,
    'price' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProjectEntry' : IDL.Func([ProjectEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeRewardCampaign' : IDL.Func([IDL.Text], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
    'createProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'createRevenueShareConfig' : IDL.Func([RevenueShareConfig], [], []),
    'createRewardCampaign' : IDL.Func([RewardCampaign], [], []),
    'createVendor' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'creditVendor' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'depositToWallet' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getAllAnalytics' : IDL.Func([], [IDL.Vec(AnalyticsEntry)], ['query']),
    'getAnalytics' : IDL.Func([IDL.Text], [IDL.Opt(AnalyticsEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyVendor' : IDL.Func([], [IDL.Opt(Vendor)], ['query']),
    'getMyVendorBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getProjectEntries' : IDL.Func([], [IDL.Vec(ProjectEntry)], ['query']),
    'getRevenueShareConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RevenueShareConfig)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendorById' : IDL.Func([IDL.Text], [IDL.Opt(Vendor)], ['query']),
    'getWallet' : IDL.Func([], [IDL.Opt(Wallet)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'joinRewardCampaign' : IDL.Func([IDL.Text], [], []),
    'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listOrdersByVendor' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProductsByVendor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'trackProjectClick' : IDL.Func([IDL.Text], [], []),
    'trackProjectView' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob, IDL.Nat],
        [],
        [],
      ),
    'updateRevenueShareConfig' : IDL.Func([RevenueShareConfig], [], []),
    'withdrawFromWallet' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'withdrawVendorBalance' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };