/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'createdAt' : bigint,
  'productId' : string,
  'totalAmount' : bigint,
  'vendorId' : Principal,
  'quantity' : bigint,
  'customerId' : Principal,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'delivered' : null };
export interface Product {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'stock' : bigint,
  'vendorId' : Principal,
  'price' : bigint,
}
export interface ProjectEntry {
  'id' : string,
  'clicks' : bigint,
  'views' : bigint,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
}
export interface RewardCampaign {
  'id' : string,
  'participants' : Array<Principal>,
  'rewardAmount' : bigint,
  'name' : string,
  'description' : string,
  'campaignType' : RewardCampaignType,
}
export type RewardCampaignType = { 'reward' : null } |
  { 'contest' : null } |
  { 'workshop' : null } |
  { 'referral' : null } |
  { 'earning' : null } |
  { 'education' : null } |
  { 'commission' : null } |
  { 'airdrop' : null } |
  { 'bonus' : null } |
  { 'special' : null } |
  { 'volunteer' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'pendingRewardCampaigns' : Array<string>,
  'name' : string,
  'createdAt' : bigint,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'bio' : string,
  'categories' : Array<string>,
  'balance' : bigint,
  'displayName' : string,
  'published' : boolean,
  'createdAt' : bigint,
  'vendorOwner' : Principal,
  'principalId' : Principal,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createProduct' : ActorMethod<[Product], undefined>,
  'createProject' : ActorMethod<[ProjectEntry], undefined>,
  'createUserProfile' : ActorMethod<[UserProfile], undefined>,
  'createVendor' : ActorMethod<[string, string, Array<string>], undefined>,
  'finishOnboarding' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getProject' : ActorMethod<[string], [] | [ProjectEntry]>,
  'getProjectAnalytics' : ActorMethod<
    [string],
    [] | [{ 'clicks' : bigint, 'views' : bigint }]
  >,
  'getProjectsByOwner' : ActorMethod<[Principal], Array<ProjectEntry>>,
  'getRewardCampaign' : ActorMethod<[string], [] | [RewardCampaign]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[Principal], UserRole>,
  'getVendor' : ActorMethod<[Principal], [] | [Vendor]>,
  'getVendorBalance' : ActorMethod<[Principal], bigint>,
  'getVendorOrders' : ActorMethod<[], Array<Order>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listOrders' : ActorMethod<[], Array<Order>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listPublicVendors' : ActorMethod<[], Array<Vendor>>,
  'listPublicVendorsByCategory' : ActorMethod<[string], Array<Vendor>>,
  'listRewardCampaigns' : ActorMethod<[], Array<RewardCampaign>>,
  'publishVendor' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unpublishVendor' : ActorMethod<[], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[string, Product], undefined>,
  'updateVendorProfile' : ActorMethod<
    [string, string, Array<string>],
    undefined
  >,
  'withdrawVendorBalance' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];