/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'vendorId' : IDL.Principal,
  'price' : IDL.Nat,
});
export const ProjectEntry = IDL.Record({
  'id' : IDL.Text,
  'clicks' : IDL.Nat,
  'views' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'pendingRewardCampaigns' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Opt(IDL.Text),
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : IDL.Int,
  'productId' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'vendorId' : IDL.Principal,
  'quantity' : IDL.Nat,
  'customerId' : IDL.Principal,
});
export const RewardCampaignType = IDL.Variant({
  'reward' : IDL.Null,
  'contest' : IDL.Null,
  'workshop' : IDL.Null,
  'referral' : IDL.Null,
  'earning' : IDL.Null,
  'education' : IDL.Null,
  'commission' : IDL.Null,
  'airdrop' : IDL.Null,
  'bonus' : IDL.Null,
  'special' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const RewardCampaign = IDL.Record({
  'id' : IDL.Text,
  'participants' : IDL.Vec(IDL.Principal),
  'rewardAmount' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'campaignType' : RewardCampaignType,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Vendor = IDL.Record({
  'bio' : IDL.Text,
  'categories' : IDL.Vec(IDL.Text),
  'balance' : IDL.Nat,
  'displayName' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
  'vendorOwner' : IDL.Principal,
  'principalId' : IDL.Principal,
});
export const VendorRatingSummary = IDL.Record({
  'averageRating' : IDL.Float64,
  'starBreakdown' : IDL.Vec(IDL.Nat),
  'vendorId' : IDL.Opt(IDL.Principal),
  'totalReviews' : IDL.Nat,
});
export const Review = IDL.Record({
  'createdAt' : IDL.Int,
  'comment' : IDL.Text,
  'vendorId' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewId' : IDL.Text,
  'authorPrincipal' : IDL.Principal,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createProduct' : IDL.Func([Product], [], []),
  'createProject' : IDL.Func([ProjectEntry], [], []),
  'createUserProfile' : IDL.Func([UserProfile], [], []),
  'createVendor' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'finishOnboarding' : IDL.Func([], [], []),
  'getAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(ProjectEntry)], ['query']),
  'getProjectAnalytics' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Record({ 'clicks' : IDL.Nat, 'views' : IDL.Nat }))],
      ['query'],
    ),
  'getProjectsByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ProjectEntry)],
      ['query'],
    ),
  'getRewardCampaign' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RewardCampaign)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
  'getVendor' : IDL.Func([IDL.Principal], [IDL.Opt(Vendor)], ['query']),
  'getVendorBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getVendorOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getVendorRatingSummary' : IDL.Func(
      [IDL.Principal],
      [VendorRatingSummary],
      ['query'],
    ),
  'getVendorReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUnpublishedVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'listAllVendorsQuery' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listProductStockByVendorId' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listPublicVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'listPublicVendorsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Vendor)],
      ['query'],
    ),
  'listRewardCampaigns' : IDL.Func([], [IDL.Vec(RewardCampaign)], ['query']),
  'publishVendor' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCategory' : IDL.Func([IDL.Text], [IDL.Vec(Vendor)], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitReview' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unpublishVendor' : IDL.Func([], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
  'updateVendorProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'verifyVendor' : IDL.Func([IDL.Principal], [], []),
  'withdrawVendorBalance' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'vendorId' : IDL.Principal,
    'price' : IDL.Nat,
  });
  const ProjectEntry = IDL.Record({
    'id' : IDL.Text,
    'clicks' : IDL.Nat,
    'views' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'pendingRewardCampaigns' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Opt(IDL.Text),
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : IDL.Int,
    'productId' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'vendorId' : IDL.Principal,
    'quantity' : IDL.Nat,
    'customerId' : IDL.Principal,
  });
  const RewardCampaignType = IDL.Variant({
    'reward' : IDL.Null,
    'contest' : IDL.Null,
    'workshop' : IDL.Null,
    'referral' : IDL.Null,
    'earning' : IDL.Null,
    'education' : IDL.Null,
    'commission' : IDL.Null,
    'airdrop' : IDL.Null,
    'bonus' : IDL.Null,
    'special' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const RewardCampaign = IDL.Record({
    'id' : IDL.Text,
    'participants' : IDL.Vec(IDL.Principal),
    'rewardAmount' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'campaignType' : RewardCampaignType,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Vendor = IDL.Record({
    'bio' : IDL.Text,
    'categories' : IDL.Vec(IDL.Text),
    'balance' : IDL.Nat,
    'displayName' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
    'vendorOwner' : IDL.Principal,
    'principalId' : IDL.Principal,
  });
  const VendorRatingSummary = IDL.Record({
    'averageRating' : IDL.Float64,
    'starBreakdown' : IDL.Vec(IDL.Nat),
    'vendorId' : IDL.Opt(IDL.Principal),
    'totalReviews' : IDL.Nat,
  });
  const Review = IDL.Record({
    'createdAt' : IDL.Int,
    'comment' : IDL.Text,
    'vendorId' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewId' : IDL.Text,
    'authorPrincipal' : IDL.Principal,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createProduct' : IDL.Func([Product], [], []),
    'createProject' : IDL.Func([ProjectEntry], [], []),
    'createUserProfile' : IDL.Func([UserProfile], [], []),
    'createVendor' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'finishOnboarding' : IDL.Func([], [], []),
    'getAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getProject' : IDL.Func([IDL.Text], [IDL.Opt(ProjectEntry)], ['query']),
    'getProjectAnalytics' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Record({ 'clicks' : IDL.Nat, 'views' : IDL.Nat }))],
        ['query'],
      ),
    'getProjectsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ProjectEntry)],
        ['query'],
      ),
    'getRewardCampaign' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RewardCampaign)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
    'getVendor' : IDL.Func([IDL.Principal], [IDL.Opt(Vendor)], ['query']),
    'getVendorBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getVendorOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getVendorRatingSummary' : IDL.Func(
        [IDL.Principal],
        [VendorRatingSummary],
        ['query'],
      ),
    'getVendorReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUnpublishedVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'listAllVendorsQuery' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listProductStockByVendorId' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listPublicVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'listPublicVendorsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Vendor)],
        ['query'],
      ),
    'listRewardCampaigns' : IDL.Func([], [IDL.Vec(RewardCampaign)], ['query']),
    'publishVendor' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCategory' : IDL.Func([IDL.Text], [IDL.Vec(Vendor)], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitReview' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unpublishVendor' : IDL.Func([], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
    'updateVendorProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'verifyVendor' : IDL.Func([IDL.Principal], [], []),
    'withdrawVendorBalance' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };